version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:80"
    restart: always
    healthcheck:
      test: curl --fail http://localhost || exit 1
      interval: 10s
      timeout: 3s
  redis:
    image: "redis:alpine"
    restart: always
